### ISSUE TITLE
Increase health when using Tough talent

### ISSUE THREAD

**Issue by jwylie01** [fvtt-fria-ligan/blade-runner-foundry-vtt#6] opened 2022-11-30 17:10 UTC
### Describe the bug

If a player has the "tough" talent their max health isn't increasing by 1.

### Reproduction

Add tough talent to the character sheet. Note the max health doesn't increase by 1 when the talent is added.

### System Info

```sh
Foundry V10 Build 290
The Forge for hosting
Blade Runner 10.0.1
Blade Runner RPG Start Set Version 1.0.1
Blade Runner RPG Core Rules Version 1.0.1
```

### Priority this issue should have?

High (a broken feature, major functional impact)

### Validations

- [X] Done a clean install of the system.
- [X] Disabled all modules.
- [X] Checked if the issue is present in a new world instance (create a new world in foundry using the Blade Runner system).

**Comment by Stefouch** [comment] 2022-12-01 08:51
Hi @jwylie01 ! Thank you for your bug report!

You can change the health & resolve maxima from the sheet config (click the ⚙️ icon in the header).

See screenshot below:
![Actor Sheet Config](https://github.com/fvtt-fria-ligan/blade-runner-foundry-vtt/blob/main/static/assets/screenshots/actor-sheet-config.png?raw=true)

Hope this solve your issue.

**Comment by Stefouch** [comment] 2022-12-01 16:19
I'm closing this because this is not a bug. Feel free to create a feature request instead if you deem it is important enough for consideration.

**Closed by Stefouch** 2022-12-01 16:19 UTC
